### ISSUE TITLE
To read LIDC-IDRI?

### ISSUE THREAD

**Issue by ejlai** [lcit/ext3DLBP#4]
This example below reads .bmp files. To have it read images from LIDC-IDRI, e.g. LIDC-IDRI-0124_GT1_1.nii.gz, this can be done by modifying this function def from_images_to_3D_array(directory, size)? Thanks.

`examples/convert_3d_texture_python/main.py
`

**Comment by lcit** [comment]
sure, the important is that at line 70 of that file the variable img3D contains your volume.
