### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by ejlai** [lcit/ext3DLBP#5]
Does the library work only for int32 data type for the 3D array?
I have this function that reads a nifti file and return a niiROI (np.ndarray with float type).

```
def readNifty(filePath):
    image = sitk.ReadImage(filePath)
    print("Reading Nifty format from {}".format(filePath))
    print("Image size: {}".format(image.GetSize()))
    metadata = Metadata(image.GetOrigin(), image.GetSpacing(), image.GetDirection())

    # Converting from SimpleITK image to Numpy array. But also is changed the coordinate systems
    # from the image which use (x,y,z) to the array using (z,y,x).
    volume_zyx = sitk.GetArrayFromImage(image)
    volume_xyz = np.transpose(volume_zyx, (2, 1, 0)) #back to the initial xyz coordinate system
    print("Volume shape: {}".format(volume_xyz.shape))
    print("Minimum value: {}".format(np.min(volume_xyz)))
    print("Maximum value: {}".format(np.max(volume_xyz)))
    return volume_xyz, metadata     # return two items.
```
When I run this, I have encountered memory error:

```
(img_3d_NI,img_3d_RD,img_3d_CI) = lbp.convert_3d_image(niiROI) #img3D

MemoryError

```
Any tips on solving this would be great.  Thanks!

**Comment by ejlai** [comment]
The problem perhaps is not just about float vs int32. I could cast the return of the define function to int32 like so: `return np.int32(volume_xyz)`

The data type of niiROI is the same as img3D and the size is a lot smaller. 

```
In [59]: niiROI.shape
Out[59]: (10, 12, 3)

In [60]: niiROI.size
Out[60]: 360

In [61]: runfile('/home/kai/msciot/test/main.py', wdir='/home/kai/msciot/test')
Reloaded modules: ext3DLBPpy, NiftyIO
Elapsed time: 38.266329765319824 [s]

In [62]: img3D.shape
Out[62]: (64, 64, 64)

In [63]: img3D.size
Out[63]: 262144
```

The problem is perhaps because this function `lbp.convert_3d_image(argument)` expects a specific argument (a numpy.ndarray with fixed size)?

**Comment by lcit** [comment]
the function `lbp.convert_3d_image(argument)` expects int32. Do you have the same MemoryError if you cast the volume to int32?

**Comment by ejlai** [comment]
Yes, the same error.  (I also restarted the IDE, spyder3). 

```
runfile('/home/kai/msciot/test/test.py', wdir='/home/kai/msciot/test')
Reloaded modules: ext3DLBPpy, NiftyIO
Reading Nifty format from ../data/test_set/CTRoi_nii/LIDC-IDRI-0124_GT1_2.nii.gz
Image size: (10, 12, 3)
Volume shape: (10, 12, 3)
Minimum value: 198.0
Maximum value: 976.0
Traceback (most recent call last):

  File "<ipython-input-7-2b875f57d76f>", line 1, in <module>
    runfile('/home/kai/msciot/test/test.py', wdir='/home/kai/msciot/test')

  File "/home/kai/.local/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/kai/.local/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/kai/msciot/test/test.py", line 69, in <module>
    (img_3d_NI,img_3d_RD,img_3d_CI) = lbp.convert_3d_image(niiROI)


MemoryError

```

**Comment by lcit** [comment]
Do you have the same error if you run the example code in `examples/convert_3d_texture_python`? If not the problem might be that dimension 2 of your volume has only 3 elements. In teory you should be able to use any descriptor with radius r=1 i.e `NI_RD_CI_LBP_P42g_R1` however from such small volume you are not going to get meaningful statistics.

As test you can try stacking your volume multiple time using `np.stack([input_volume]*3, 2)`.

**Comment by ejlai** [comment]
Yes, the example (`ext3DLBP/examples/convert_3d_texture_python/main.py`) works fine. Right! The problem perhaps is due to a small volume. When I tried a file with large volume, it generates plots similar to the example.  This large nii file has the following info:

```
In[5]: nii.size
Out[5]: 476280

In[6]: nii.shape
Out[6]: (105, 108, 42)
```
I still wish it runs with case of small volume (10, 12, 3) so that I can have it to compare with non 3D LBP.

The library doesn't support float though. Why int only? Can I modify somewhere to have it support float, if makes any difference to the result? Thank you very much!

`TypeError: No registered converter was able to produce a C++ rvalue of type int from this Python object of type numpy.float64`

**Comment by lcit** [comment]
Have you tried using radius 1 descriptors i.e. `NI_RD_CI_LBP_P42g_R1` on your small volume? It should work. Regarding the input type, the library was developed to work with images and hence integer types. in any case, using floats rather than integers does not make much difference as the values are thresholded at some point. If the values in your input volume ranges as an example from 0 to 1 then you have to scale the amplitude to have more resolution. The type int32 ranges from -2147483648 to 2147483647 which allows you to have very high resolution anyhow.

**Comment by ejlai** [comment]
This works well. Thank you very much! I am going to read your paper to see if there are more descriptions about the library.

**Comment by ejlai** [comment]
This works well. Thank you very much! I am going to read your paper to see if there are more descriptions about the library.
