### ISSUE TITLE
python3: malloc.c:4023: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed

### ISSUE THREAD

**Issue by ejlai** [lcit/ext3DLBP#6]
I was testing the model (`lbp = ext3DLBPpy.NI_RD_CI_LBP_P42g_R1(mur, V)`) with 50+ nii.gz files. The first 22 files were fine. But when it comes to processing the 23rd file, this error occurred. I have tried different spatial resolution, but the error is the same. 

```
$ python3 test.py 
Reading Nifty format from .../training/LIDC-IDRI-0385_GT1_1.nii.gz
Image size: (15, 18, 15)
Volume shape: (15, 18, 15)
Minimum value: 48.0
Maximum value: 2009.0
python3: malloc.c:4023: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
Aborted (core dumped)
```
I have no idea what this error suggests. What might be the problem, do you think? Thanks.

**Comment by lcit** [comment]
could you please check if the Ram memory increases continuously? In Windows use `Task Manager`, Linux use `htop`

**Comment by ejlai** [comment]
The RAM (the os is in a VirtualBox) roughly stays the same. 

<img width="502" alt="RAM" src="https://user-images.githubusercontent.com/38882183/60208309-409bb100-9858-11e9-9780-6435f66f823c.PNG">

But if I try to loop through all the 52 images to generate LBP codes one by one, then the error is different:

```
...
Reading Nifty format from /home/kai/msciot/data/training/LIDC-IDRI-0285_GT1_1.nii.gz
Image size: (12, 11, 6)
Volume shape: (12, 11, 6)
Minimum value: 0.0
Maximum value: 1533.0
compute LBP...
Append histograms...
Reading Nifty format from /home/kai/msciot/data/training/LIDC-IDRI-0289_GT1_1.nii.gz
Image size: (30, 41, 11)
Volume shape: (30, 41, 11)
Minimum value: 0.0
Maximum value: 1988.0
compute LBP...
Append histograms...
Reading Nifty format from /home/kai/msciot/data/training/LIDC-IDRI-0385_GT1_1.nii.gz
Image size: (15, 18, 15)
Volume shape: (15, 18, 15)
Minimum value: 48.0
Maximum value: 2009.0
compute LBP...
**free(): corrupted unsorted chunks
Aborted (core dumped)**

```

**Comment by ejlai** [comment]
I just tried updating and rebooting the OS. 

Then run it first time:
```
...
Reading Nifty format from /home/kai/msciot/data/training/LIDC-IDRI-0246_GT1_1.nii.gz
Image size: (15, 15, 5)
Volume shape: (15, 15, 5)
Minimum value: 0.0
Maximum value: 3351.0
compute LBP...
Append histograms...
Reading Nifty format from /home/kai/msciot/data/training/LIDC-IDRI-0247_GT1_1.nii.gz
Image size: (7, 9, 3)
Volume shape: (7, 9, 3)
Minimum value: 50.0
Maximum value: 1238.0
compute LBP...
Append histograms...
free(): invalid pointer
Aborted (core dumped)
```

Run it a second time, getting different error:

```
...
Reading Nifty format from /home/kai/msciot/data/training/LIDC-IDRI-0247_GT1_1.nii.gz
Image size: (7, 9, 3)
Volume shape: (7, 9, 3)
Minimum value: 50.0
Maximum value: 1238.0
compute LBP...
Append histograms...
Reading Nifty format from /home/kai/msciot/data/training/LIDC-IDRI-0249_GT1_1.nii.gz
Image size: (16, 14, 8)
Volume shape: (16, 14, 8)
Minimum value: 0.0
Maximum value: 1501.0
compute LBP...
double free or corruption (!prev)
Aborted (core dumped)

```
Run it a third time:

```
...
Reading Nifty format from /home/kai/msciot/data/training/LIDC-IDRI-0289_GT1_1.nii.gz
Image size: (30, 41, 11)
Volume shape: (30, 41, 11)
Minimum value: 0.0
Maximum value: 1988.0
compute LBP...
Append histograms...
Reading Nifty format from /home/kai/msciot/data/training/LIDC-IDRI-0385_GT1_1.nii.gz
Image size: (15, 18, 15)
Volume shape: (15, 18, 15)
Minimum value: 48.0
Maximum value: 2009.0
compute LBP...
free(): corrupted unsorted chunks
Aborted (core dumped)

```

**Comment by lcit** [comment]
I managed to find the problem, I made an error in mapping volumes to vectors in the python wrapper c code. Now is fixed and the unit tests are ok.
Please pull the changes form the repo and re-compile the wrapper.
Let me know if the problem is fixed on your side as well.

**Comment by ejlai** [comment]
Thanks for the quick response!! I think you fixed it. I can now run this method (` lbp = ext3DLBPpy.NI_RD_CI_LBP_P42g_R1(mur, V)` ) for all files. 

Here's what I have done.
Clone the project from another location:
```
kai@kai-VirtualBox:~$ git clone https://github.com/lcit/ext3DLBP.git
kai@kai-VirtualBox:~$ cd ext3DLBP/python_wrapper
```

In my case, to avoid "Could NOT find Boost" error, edit build.sh and change this line:
`cmake -D Boost_LIBRARY_DIR=/usr/local/lib -DBoost_INCLUDE_DIR=/usr/local/include ..`
to
`cmake -D Boost_LIBRARY_DIR=/usr/local/lib -DBoost_DEBUG=True -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DBoost_INCLUDE_DIR=/usr/local/include ..
`
Now build it:
`kai@kai-VirtualBox:~/ext3DLBP/python_wrapper$ ./build.sh 
`
Edit this file .bashrc in home directory to include:
`export PYTHONPATH="/home/kai/ext3DLBP/python_wrapper/build:$PYTHONPATH"
`
(With the environment setting, it is no longer needed to set the path in the py script like so:
`sys.path.insert(0,'/home/kai/ext3DLBP/python_wrapper'` )
 
Although I would still have the old issue for high spatial resolution method, e.g. (2,42), (1,92)

```
Traceback (most recent call last):
  File "PrepareData.py", line 82, in <module>
    (img_3d_NI,img_3d_RD,img_3d_CI) = lbp.convert_3d_image(nii)
MemoryError

```
I may try some method you mentioned by stacking up volume and test it.
