### ISSUE TITLE
joint vs concatenate? 

### ISSUE THREAD

**Issue by ejlai** [lcit/ext3DLBP#7]
Hello...
In your paper, the joint of NI/RD shows promising results (classification accuracy hits 94.6% for sample rate: 1, 42) and I'd like to reproduce the method for experiments. However the result of that using the given construct_histograms function, was a 3 dimensional array:
`joint_2d = np.outer(hist1,hist2) #Joint: NI/RD` #(52, 12, 12)

While the concatenations are 2 dimensional (which can be fed to classifiers):
```
concat_of_ni_rd = np.concatenate([hist1,hist2]) #Concatenation: NI+RD, #(52, 24)
concat_of_ni_rd_ci = np.concatenate([hist1,hist2,hist3]) #Concatenation: NI+RD+CI #(52, 36)
```
What should it be done to make the joint vectors be ready for training? Thanks!

**Comment by lcit** [comment]
You simply flatten it using numy.flatten() or numpy.ravel().

**Comment by ejlai** [comment]
Ok, thanks for the quick tips! Now if it gets flatten `X_train_joint_ni_rd = X_train_joint_ni_rd.flatten()`, I have a result like this

 ```
X_train_joint_ni_rd.shape
Out[69]: (7488,)
```

I have 52 rows which were matched with the y_train #size of (52,)
Do I need to do something to ensure it has 52 rows so it can be trained with the y data set? Thank you very much!

**Comment by ejlai** [comment]
I think this method may work as it keeps the row numbers (52):
```
c = X_train_joint_ni_rd.flatten().reshape(X_train_joint_ni_rd.shape[0],X_train_joint_ni_rd.shape[1]*X_train_joint_ni_rd.shape[2]) 

c.shape
Out[86]: (52, 144)
```

Feel free to close this if you agree. Thanks!

**Comment by lcit** [comment]
I'm not sure I'm understanding your question. If you have N samples you will have N feature vectors of shape (M,1) describing the N volumes and N labels associated to each volume or chunk of volume; in case of binary classification the labels $\in {0,1}$.

**Comment by ejlai** [comment]
What I did gives me the data format I  was looking for. In my case, I have 52 samples, e.g. `X_train.shape:  (52, 12, 12)`. 52 labels (y_train), e.g.` (52,) `associated to them. So if this X_train, a 3D array, `(52, 12, 12) ` gets  flatten to  1D array, ` (7488,) `with  `X_train =  X_train.flatten()`, which seems to result in the loss of the feature number. (Unless it has 52 samples? ).  I am not sure how the math behind it works but this way of flattening it, `X_train = X_train.flatten().reshape(X_train.shape[0],X_train.shape[1]*X_train.shape[2])`, resulting `X_train.shape: (52, 144)` (52 samples, 144 features), then I can use that with a classifier. I will have to test it a bit more.

**Comment by lcit** [comment]
X_train is one sample or contains all the samples? If contains all the samples it means that one of your samples as size (12,12)

**Comment by ejlai** [comment]
X_train in this case is the joint of NI/RD 3D LBP histograms from 52 samples using 12 bins, sample rate (1,42), V=3. So 12 should be features from NI, and RD accordingly.

**Comment by ejlai** [comment]
So in this case, join of NI/RD should be vertical stack (12 features), while concatenation of the NI+RD should be horizontal stack (24 features)? But according to the sample code below:

```
def construct_histograms(img_3d_NI, img_3d_RD, img_3d_CI, bins):
    (hist1, edges) = np.histogram(img_3d_NI, bins=np.arange(0,bins+1), density=False)       
    (hist2, edges) = np.histogram(img_3d_RD, bins=np.arange(0,bins+1), density=False)
    (hist3, edges) = np.histogram(img_3d_CI, bins=np.arange(0,2+1), density=False)    
    joint_2d = np.outer(hist1,hist2)
    joint_3d = np.repeat(joint_2d[:, :, np.newaxis], len(hist3), axis=2)*hist3
    concat = np.concatenate([hist1,hist2,hist3])
    return joint_3d, concat, hist1, hist2, hist3

```

joint ( NI/RD ) is this:  `joint_2d = np.outer(hist1,hist2)`
concatenation (NI+RD) the two would be:  `concat = np.concatenate([hist1,hist2])`

That's what I used.

**Comment by lcit** [comment]
For NI/RD only use this:
```
def construct_histogram_NI_RD(img_3d_NI, img_3d_RD, bins):
    (hist1, edges) = np.histogram(img_3d_NI, bins=np.arange(0,bins+1), density=False)       
    (hist2, edges) = np.histogram(img_3d_RD, bins=np.arange(0,bins+1), density=False)   
    joint_2d = np.outer(hist1,hist2).ravel()
    concat = np.concatenate([hist1,hist2])
    return joint_2d, concat, hist1, hist2
```
For NI/RD/CI use this:
```
def construct_histogram_NI_RD_CI(img_3d_NI, img_3d_RD, img_3d_CI, bins):
    (hist1, edges) = np.histogram(img_3d_NI, bins=np.arange(0,bins+1), density=False)       
    (hist2, edges) = np.histogram(img_3d_RD, bins=np.arange(0,bins+1), density=False)
    (hist3, edges) = np.histogram(img_3d_CI, bins=np.arange(0,2+1), density=False)    
    joint_2d = np.outer(hist1,hist2)
    joint_3d = np.repeat(joint_2d[:, :, np.newaxis], len(hist3), axis=2)*hist3
    joint_3d = joint_3d.ravel()
    concat = np.concatenate([hist1,hist2,hist3])
    return joint_3d, concat, hist1, hist2, hist3
```
Regarding the number of bins `bins ` I suggest using the default one provided by the object `lbp.bins` otherwise you may lose information or make it sparse.

**Comment by ejlai** [comment]
Perfect. Thank you very much! My thought was to examine different number of bins to see which has better accuracy for model training...bins number for HOG analysis seems  to make a difference.  But I should  include the default as well.
